// examples/timer/src/Timer.tsx
import { useAtomValue } from "jotai";
import { useBunja } from "bunja/react";
import { timerBunja } from "./state/timer.ts";
import { ItemScope } from "./state/item.ts";
import { TitleEditor } from "./TitleEditor.tsx";

interface Props {
  id: number;
  onRemove(): void;
}

export function Timer({ id, onRemove }: Props) {
  const {
    timerAtom,
    secondsAtom,
    millisecondsAtom,
    start,
    stop,
    reset,
    titleAtom,
    editingTitleAtom,
  } = useBunja(timerBunja, [ItemScope.bind(id)]);
  const { running } = useAtomValue(timerAtom);
  const seconds = useAtomValue(secondsAtom);
  const ms = useAtomValue(millisecondsAtom);

  return (
    <div className="timer-item">
      <TitleEditor
        titleAtom={titleAtom}
        editingTitleAtom={editingTitleAtom}
        icon="⏱️"
      />

      <div className={`timer-status ${running ? "running" : "stopped"}`} />

      <div className="timer-display">
        <div className={`timer-time ${running ? "running" : ""}`}>
          {seconds}:{ms}
        </div>
      </div>

      <div className="timer-controls">
        {running
          ? (
            <button
              type="button"
              className="timer-btn danger"
              onClick={stop}
            >
              Stop
            </button>
          )
          : (
            <button
              type="button"
              className="timer-btn success"
              onClick={start}
            >
              Start
            </button>
          )}

        <button
          type="button"
          className="timer-btn secondary"
          onClick={reset}
        >
          Reset
        </button>

        <button
          type="button"
          className="timer-btn primary"
          onClick={onRemove}
        >
          Remove
        </button>
      </div>
    </div>
  );
}

// examples/timer-solid/src/Timer.tsx
import { timerBunja } from "./state/timer.ts";
import { ItemScope } from "./state/item.ts";
import { TitleEditor } from "./TitleEditor.tsx";
import { useBunja } from "bunja/solid";
import { createEffect, Show } from "solid-js";

interface Props {
  id: number;
  onRemove(): void;
}

export function Timer(props: Props) {
  const timer = useBunja(timerBunja, () => [ItemScope.bind(props.id)]);

  createEffect(() => {
    console.log(timer().title());
  });

  return (
    <div class="timer-item">
      <TitleEditor
        title={timer().title()}
        setTitle={timer().setTitle}
        editingTitle={timer().editingTitle()}
        setEditingTitle={timer().setEditingTitle}
        icon="⏱️"
      />

      <div
        class={`timer-status ${timer().timer.running ? "running" : "stopped"}`}
      />

      <div class="timer-display">
        <div class={`timer-time ${timer().timer.running ? "running" : ""}`}>
          {timer().seconds()}:{timer().milliseconds()}
        </div>
      </div>

      <div class="timer-controls">
        <Show
          when={timer().timer.running}
          fallback={
            <button
              type="button"
              class="timer-btn success"
              onClick={timer().start}
            >
              Start
            </button>
          }
        >
          <button
            type="button"
            class="timer-btn danger"
            onClick={timer().stop}
          >
            Stop
          </button>
        </Show>

        <button
          type="button"
          class="timer-btn secondary"
          onClick={timer().reset}
        >
          Reset
        </button>

        <button
          type="button"
          class="timer-btn primary"
          onClick={props.onRemove}
        >
          Remove
        </button>
      </div>
    </div>
  );
}
