// examples/timer-solid/src/App.tsx
import { useBunja } from "bunja/solid";
import { Timer } from "./Timer.tsx";
import { Countdown } from "./Countdown.tsx";
import { appBunja } from "./state/app.ts";
import { Dynamic } from "solid-js/web";
import { For, Show } from "solid-js";

export function App() {
  const app = useBunja(appBunja);

  return (
    <div class="timer-app">
      <header class="timer-header">
        <h1>Bunja Timers</h1>
      </header>

      <section class="add-timer-section">
        <button
          type="button"
          class="add-timer-btn"
          onClick={app().addTimer}
        >
          Add new timer
        </button>
        <button
          type="button"
          class="add-timer-btn"
          onClick={app().addCountdown}
        >
          Add new countdown
        </button>
      </section>

      <section class="timer-list">
        <For
          each={app().items}
          fallback={
            <div class="empty-state">
              <h3>No timers or countdowns yet</h3>
              <p>Add a timer or countdown to get started!</p>
            </div>
          }
        >
          {(item) => (
            <Dynamic
              component={item.type === "timer" ? Timer : Countdown}
              id={item.id}
              onRemove={() => app().remove(item.id)}
            />
          )}
        </For>
      </section>

      <Show when={app().items.length}>
        {(length) => (
          <footer class="timer-footer">
            {length()} item{length() !== 1 ? "s" : ""} total
          </footer>
        )}
      </Show>
    </div>
  );
}

// examples/timer/src/App.tsx
import { useAtomValue } from "jotai";
import { useBunja } from "bunja/react";
import { Timer } from "./Timer.tsx";
import { Countdown } from "./Countdown.tsx";
import { appBunja, type Item } from "./state/app.ts";

export function App() {
  const { itemsAtom, addTimer, addCountdown, remove } = useBunja(
    appBunja,
  );
  const items = useAtomValue(itemsAtom);

  const renderItem = (item: Item) => {
    const commonProps = {
      id: item.id,
      onRemove: () => remove(item.id),
    };

    return item.type === "timer"
      ? <Timer key={item.id} {...commonProps} />
      : <Countdown key={item.id} {...commonProps} />;
  };

  return (
    <div className="timer-app">
      <header className="timer-header">
        <h1>Bunja Timers</h1>
      </header>

      <section className="add-timer-section">
        <button
          type="button"
          className="add-timer-btn"
          onClick={addTimer}
        >
          Add new timer
        </button>
        <button
          type="button"
          className="add-timer-btn"
          onClick={addCountdown}
        >
          Add new countdown
        </button>
      </section>

      <section className="timer-list">
        {items.length === 0
          ? (
            <div className="empty-state">
              <h3>No timers or countdowns yet</h3>
              <p>Add a timer or countdown to get started!</p>
            </div>
          )
          : (
            items.map(renderItem)
          )}
      </section>

      {items.length > 0 && (
        <footer className="timer-footer">
          {items.length} item{items.length !== 1 ? "s" : ""} total
        </footer>
      )}
    </div>
  );
}
